spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dms
    username: root
    password: Vb.0541134085
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true